"use client";

import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { api, type AnalysisResult, type CreditReport } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge, statusVariant } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton, SkeletonCard } from "@/components/ui/skeleton";
import { ScoreRing } from "@/components/ui/charts";
import { ComplianceBanner } from "@/components/ui/compliance-banner";
import { EmptyState } from "@/components/ui/empty-state";
import { formatCurrency, formatDate, cn } from "@/lib/utils";
import {
  AlertTriangle,
  Download,
  FileText,
  Sparkles,
  ArrowRight,
  RefreshCw,
} from "@/components/ui/icons";

const severityStyles = {
  high: { badge: "danger" as const, bar: "bg-gradient-to-r from-rose-500 to-red-500", text: "text-rose-500" },
  medium: { badge: "warning" as const, bar: "bg-gradient-to-r from-amber-500 to-orange-400", text: "text-amber-500" },
  low: { badge: "info" as const, bar: "bg-gradient-to-r from-cyan-500 to-blue-500", text: "text-cyan-500" },
};

export default function ReportDetailPage() {
  const { id } = useParams<{ id: string }>() ?? { id: "" };

  const { data: report, isLoading } = useQuery({
    queryKey: ["report", id],
    queryFn: () => api.get<CreditReport>(`/reports/${id}`),
  });

  const { data: analysis, isLoading: analysisLoading } = useQuery({
    queryKey: ["analysis", id],
    queryFn: () => api.get<{ status: string; analysisJson: AnalysisResult | null; summary: Record<string, number> | null }>(`/analysis/reports/${id}`),
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      return status === "ANALYZING" || status === "PARSING" ? 2500 : false;
    },
  });

  const result = analysis?.analysisJson;

  if (isLoading || !report) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-64" />
        <div className="grid gap-6 lg:grid-cols-3">
          <SkeletonCard lines={3} className="lg:col-span-2 h-72" />
          <SkeletonCard lines={4} className="h-72" />
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <Link href="/reports" className="text-sm text-slate-400 hover:text-brand-500">
            ← Reports
          </Link>
          <h1 className="mt-1 text-2xl font-bold tracking-tight">{report.filename}</h1>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            {report.client.name} · {report.bureau} · Uploaded {formatDate(report.createdAt)}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant={statusVariant(report.status)}>{report.status.replace("_", " ")}</Badge>
          <a href={`/api/reports/${report.id}/download`}>
            <Button variant="outline" size="sm">
              <Download className="h-4 w-4" /> Original file
            </Button>
          </a>
        </div>
      </motion.div>

      {(analysis?.status === "ANALYZING" || analysis?.status === "PARSING") && (
        <div className="flex items-center gap-3 rounded-2xl border border-brand-500/25 bg-brand-500/5 px-5 py-4">
          <RefreshCw className="h-5 w-5 animate-spin text-brand-500" />
          <div>
            <p className="text-sm font-semibold">AI analysis in progress</p>
            <p className="text-xs text-slate-400">Our credit analyst is reviewing {report.accounts.length} tradelines…</p>
          </div>
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Findings */}
        <div className="space-y-6 lg:col-span-2">
          <Card>
            <CardHeader className="flex-row items-center justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-brand-500" /> AI findings
                </CardTitle>
                <CardDescription>
                  {result
                    ? `${result.findings.length} findings · generated by ${result.generatedBy.replace("-", " ")}`
                    : "Analysis not available yet"}
                </CardDescription>
              </div>
              {result && (
                <Badge variant="success">
                  Potential gain: +{result.potentialGain} pts
                </Badge>
              )}
            </CardHeader>
            <CardContent>
              {analysisLoading || !result ? (
                <div className="space-y-3">
                  {Array.from({ length: 3 }).map((_, i) => (
                    <Skeleton key={i} className="h-24 w-full" />
                  ))}
                </div>
              ) : result.findings.length === 0 ? (
                <EmptyState
                  icon={<Sparkles className="h-6 w-6" />}
                  title="No findings detected"
                  description="The engine found no clear errors in this report. Great news!"
                />
              ) : (
                <div className="space-y-3">
                  {result.findings.map((f, idx) => {
                    const s = severityStyles[f.severity];
                    return (
                      <motion.div
                        key={f.id}
                        initial={{ opacity: 0, y: 12 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: idx * 0.06 }}
                        className="rounded-2xl border border-white/6 bg-white/3 p-4"
                      >
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <div className="flex items-center gap-2.5">
                            <AlertTriangle className={cn("h-4 w-4", s.text)} />
                            <p className="text-sm font-semibold">{f.title}</p>
                          </div>
                          <div className="flex items-center gap-2">
                            <Badge variant={s.badge}>{f.severity}</Badge>
                            <Badge variant="neutral">{Math.round(f.confidence * 100)}% conf.</Badge>
                            {f.disputeLetter && <Badge variant="violet">{f.disputeLetter}</Badge>}
                          </div>
                        </div>
                        <div className="mt-2.5">
                          <div className={cn("h-1 w-full rounded-full bg-slate-200/60 dark:bg-white/8")}>
                            <div className={cn("h-1 rounded-full", s.bar)} style={{ width: `${f.confidence * 100}%` }} />
                          </div>
                        </div>
                        <p className="mt-3 text-sm leading-relaxed text-slate-500 dark:text-slate-400">{f.description}</p>
                        <p className="mt-2 rounded-lg bg-brand-500/5 px-3 py-2 text-[13px] text-brand-700 dark:text-brand-300">
                          💡 {f.recommendation}
                        </p>
                      </motion.div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>

          {/* Accounts */}
          <Card>
            <CardHeader>
              <CardTitle>Tradelines</CardTitle>
              <CardDescription>{report.accounts.length} accounts on this report</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto scrollbar-thin">
                <table className="w-full min-w-[640px] text-sm">
                  <thead>
                    <tr className="border-b border-white/6 text-left text-xs uppercase tracking-wide text-slate-400">
                      <th className="pb-2.5 pr-4 font-medium">Account</th>
                      <th className="pb-2.5 pr-4 font-medium">Status</th>
                      <th className="pb-2.5 pr-4 font-medium">Balance</th>
                      <th className="pb-2.5 pr-4 font-medium">Limit</th>
                      <th className="pb-2.5 pr-4 font-medium">Last reported</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.accounts.map((a) => (
                      <tr key={a.id} className={cn("border-b border-white/4", a.isNegative && "bg-rose-500/4")}>
                        <td className="py-3 pr-4">
                          <p className="font-medium">{a.accountName}</p>
                          <p className="text-xs text-slate-400">{a.accountType}</p>
                        </td>
                        <td className="py-3 pr-4">
                          {a.isNegative ? (
                            <Badge variant="danger">{a.status ?? "Negative"}</Badge>
                          ) : (
                            <Badge variant="success">{a.status ?? "Current"}</Badge>
                          )}
                        </td>
                        <td className="py-3 pr-4 font-medium">{formatCurrency(a.balance)}</td>
                        <td className="py-3 pr-4 text-slate-400">{a.creditLimit ? formatCurrency(a.creditLimit) : "—"}</td>
                        <td className="py-3 text-slate-400">{formatDate(a.lastReportedDate)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Score snapshot</CardTitle>
            </CardHeader>
            <CardContent className="flex justify-center py-4">
              {report.scoreSnapshots[0] ? (
                <ScoreRing score={report.scoreSnapshots[0].score} label={report.scoreSnapshots[0].bureau} size={150} />
              ) : (
                <p className="py-6 text-sm text-slate-400">No score on this report</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Strategy</CardTitle>
            </CardHeader>
            <CardContent>
              {result?.strategy ? (
                <div>
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-brand-500" />
                    <Badge variant="success">{Math.round(result.strategy.confidence * 100)}% confidence</Badge>
                  </div>
                  <p className="mt-3 text-sm font-medium leading-relaxed">{result.strategy.recommendation}</p>
                  <p className="mt-2 text-xs leading-relaxed text-slate-400">{result.strategy.rationale}</p>
                  <Link href="/letters" className="mt-4 block">
                    <Button className="w-full" size="sm">
                      Generate a letter <ArrowRight className="h-4 w-4" />
                    </Button>
                  </Link>
                </div>
              ) : (
                <p className="text-sm text-slate-400">Waiting for analysis…</p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Disputes</CardTitle>
            </CardHeader>
            <CardContent>
              {report.disputes.length === 0 ? (
                <p className="text-sm text-slate-400">No disputes linked to this report.</p>
              ) : (
                <div className="space-y-2">
                  {report.disputes.map((d) => (
                    <Link key={d.id} href={`/disputes/${d.id}`} className="flex items-center justify-between rounded-xl border border-white/6 bg-white/3 p-3 transition-colors hover:bg-white/6">
                      <span className="truncate text-sm font-medium">{d.title}</span>
                      <Badge variant={statusVariant(d.status)}>R{d.currentRound}</Badge>
                    </Link>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>

          {report.inquiries.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Inquiries</CardTitle>
                <CardDescription>{report.inquiries.length} on this report</CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                {report.inquiries.map((i) => (
                  <div key={i.id} className="flex items-center justify-between text-sm">
                    <span className="text-slate-500 dark:text-slate-400">{i.company}</span>
                    <span className="text-xs text-slate-400">{formatDate(i.date)}</span>
                  </div>
                ))}
              </CardContent>
            </Card>
          )}

          <ComplianceBanner />
        </div>
      </div>
    </div>
  );
}
